language: csharp
mono: none
git:
  quiet: true

global:
- DOTNET_SKIP_FIRST_TIME_EXPERIENCE=true
- DOTNET_CLI_TELEMETRY_OPTOUT=1

jobs:
  include:
  - stage: Windows
    - os: windows
      language: csharp
      install:
      - choco install dotnetcore-sdk
      - dotnet restore
      script:
      - dotnet clean -v m
      - dotnet build
      - dotnet test
      - powershell -c "Set-ExecutionPolicy -ExecutionPolicy Unrestricted -Scope LocalMachine"
      - powershell ./CompileTest.ps1
  - stage: Linux
    - os: linux
      language: csharp
      dotnet: 3.1
      mono: none
      addons:
        apt:
          packages:
          - coreutils
      install:
      - dotnet restore
      script:
      - dotnet clean -v m --nologo
      - dotnet build --nologo
      - dotnet test --nologo
      - sudo chmod +x ./CompileTest.sh
      - sudo ./CompileTest.sh
