language: csharp
mono: none
git:
  quiet: true

before_install:
- set -e

matrix:
  include:
    - os: linux
      name: Linux
      dotnet: 3.1
      scipt:
      - dotnet test
      - sh ./generatecoverage.sh
    - os: windows
      name: Windows
      install:
      - choco install dotnetcore-sdk
      - powershell -c "Set-ExecutionPolicy -ExecutionPolicy Unrestricted -Scope LocalMachine"
      script:
      - dotnet test
      - powershell ./Generate-CoverageReport.ps1

