language: csharp
mono: none
git:
  quiet: true

before_install:
- set -e

matrix:
  include:
    - os: linux
      name: Linux
      dotnet: 3.1
      addons:
        apt:
          packages:
          - coreutils
      scipt:
      - sh ./generatecoverage.sh
    - os: windows
      name: Windows
      install:
      - choco install dotnetcore-sdk
      script:
      - powershell ./Generate-CoverageReport.ps1

script:
- dotnet restore
- dotnet test

