language: csharp
mono: none
git:
  quiet: true

script:
  - dotnet restore
  - dotnet clean -v m
  - dotnet build
  - dotnet test

matrix:
  include:
  - name: "Windows build"
    os: windows
    before_install:
    - choco install dotnetcore-sdk
    after_success:
    - powershell.exe -c "Set-ExecutionPolicy -ExecutionPolicy Unrestricted -Scope LocalMachine"
    - powershell.exe ./CompileTest.ps1
  - name: "Linux build"
    os: linux
    dotnet: 3.1
    after_success:
    - sudo chmod +x ./CompileTest.sh
    - sudo ./CompileTest.sh

# jobs:
#   include:
#   - os: windows
#     language: csharp
#     install:
#     - choco install dotnetcore-sdk
#     - dotnet restore
#     script:
#     - dotnet clean -v m
#     - dotnet build
#     - dotnet test
#     - powershell -c "Set-ExecutionPolicy -ExecutionPolicy Unrestricted -Scope LocalMachine"
#     - powershell ./CompileTest.ps1
#   - os: linux
#     language: csharp
#     dotnet: 3.1
#     mono: none
#     addons:
#       apt:
#         packages:
#         - coreutils
#     install:
#     - dotnet restore
#     script:
#     - dotnet clean -v m --nologo
#     - dotnet build --nologo
#     - dotnet test --nologo
#     - sudo chmod +x ./CompileTest.sh
#     - sudo ./CompileTest.sh
