language: csharp
mono: none
dotnet: 3.1
git:
  quiet: true
os:
- linux

install:
- dotnet restore

script:
- dotnet clean -v m --nologo
- dotnet build --nologo
- dotnet test --nologo

global:
- DOTNET_SKIP_FIRST_TIME_EXPERIENCE=true
- DOTNET_CLI_TELEMETRY_OPTOUT=1

jobs:
  include:
  - os: windows
    language: c
    install:
    - choco install dotnetcore
    script:
    - C:\Program Files\dotnet\dotnet restore
    - C:\Program Files\dotnet\dotnet clean -v m
    - C:\Program Files\dotnet\dotnet build
    - C:\Program Files\dotnet\dotnet test
  - os: linux
    language: csharp
    dotnet: 3.1
    mono: none
