
language: csharp
mono: none
git:
  quiet: true

matrix:
  include:
  - name: "Windows build"
    os: windows
    install:
    - choco install dotnetcore-sdk
    script:
    - dotnet restore
    - dotnet clean -v m
    - dotnet build
    - dotnet test
    - powershell.exe -c "Set-ExecutionPolicy -ExecutionPolicy Unrestricted -Scope LocalMachine"
    - powershell.exe ./CompileTest.ps1
  - name: "Linux build"
    os: linux
    install:
    - wget https://packages.microsoft.com/config/ubuntu/18.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
    - sudo dpkg -i packages-microsoft-prod.deb
    - sudo add-apt-repository universe
    - sudo apt-get update
    - sudo apt-get install apt-transport-https
    - sudo apt-get update
    - sudo apt-get install dotnet-sdk-3.1
    - dotnet clean -v m --nologo
    - dotnet build --nologo
    - dotnet test --nologo
    - sudo chmod +x ./CompileTest.sh
    - sudo ./CompileTest.sh

# jobs:
#   include:
#   - os: windows
#     language: csharp
#     install:
#     - choco install dotnetcore-sdk
#     - dotnet restore
#     script:
#     - dotnet clean -v m
#     - dotnet build
#     - dotnet test
#     - powershell -c "Set-ExecutionPolicy -ExecutionPolicy Unrestricted -Scope LocalMachine"
#     - powershell ./CompileTest.ps1
#   - os: linux
#     language: csharp
#     dotnet: 3.1
#     mono: none
#     addons:
#       apt:
#         packages:
#         - coreutils
#     install:
#     - dotnet restore
#     script:
#     - dotnet clean -v m --nologo
#     - dotnet build --nologo
#     - dotnet test --nologo
#     - sudo chmod +x ./CompileTest.sh
#     - sudo ./CompileTest.sh
