language: csharp
mono: none
dotnet: 3.1
git:
  quiet: true
os:
- linux

install:
- dotnet restore

script:
- dotnet clean
- dotnet build
- dotnet test

global:
- DOTNET_SKIP_FIRST_TIME_EXPERIENCE=true
- DOTNET_CLI_TELEMETRY_OPTOUT=1
