language: csharp
mono: none
dotnet: 3.1
git:
  quiet: true
os:
- linux

install:
- dotnet restore

script:
- dotnet clean -v m --nologo
- dotnet build --nologo
- dotnet test --nologo

global:
- DOTNET_SKIP_FIRST_TIME_EXPERIENCE=true
- DOTNET_CLI_TELEMETRY_OPTOUT=1

jobs:
  include:
  - os: windows
    language: c
    install:
    - choco install dotnetcore --version=3.1.1
    script:
    - dotnet restore
    - dotnet clean -v m --nologo
    - dotnet build --nologo
    - dotnet test --nologo
  - os: linux
    language: csharp
    dotnet: 3.1
    mono: none
