language: csharp
mono: none
dotnet: 3.1
git:
  quiet: true
os:
- linux

install:
- dotnet restore

script:
- dotnet clean -v m --nologo
- dotnet build --nologo
- dotnet test -v n --nologo --no-build

global:
- DOTNET_SKIP_FIRST_TIME_EXPERIENCE=true
- DOTNET_CLI_TELEMETRY_OPTOUT=1
