language: csharp
mono: none
git:
  quiet: true

global:
- DOTNET_SKIP_FIRST_TIME_EXPERIENCE=true
- DOTNET_CLI_TELEMETRY_OPTOUT=1

jobs:
  include:
  - os: windows
    language: csharp
    install:
    - choco install dotnetcore-sdk
    - dotnet restore
    script:
    - dotnet clean -v m
    - dotnet build
    - dotnet test
    - powershell ./CompileTest.ps1
  - os: linux
    language: csharp
    dotnet: 3.1
    mono: none
    addons:
      apt:
        packages:
        - coreutils
    install:
    - dotnet restore
    script:
    - dotnet clean -v m --nologo
    - dotnet build --nologo
    - dotnet test --nologo
    - sudo ./CompileTest.sh
