language: csharp
mono: none
git:
  quiet: true

matrix:
  include:
    - os: linux
    - os: windows

script: 
- echo "OS is $TRAVIS_OS_NAME";
- if [ "$TRAVIS_OS_NAME" = "linux" ]; then bash "$TRAVIS_BUILD_DIR"/tools/travis/build-linux.sh; fi
- if [ "$TRAVIS_OS_NAME" = "windows" ]; then bash "$TRAVIS_BUILD_DIR"/tools/travis/build-windows.sh; bash "$TRAVIS_BUILD_DIR"/tools/travis/test-windows.sh; fi

# matrix:
#   include:
#   - name: "Windows build"
#     os: windows
#     before_install:
#     - choco install dotnetcore-sdk
#     after_success:
#     - powershell.exe -c "Set-ExecutionPolicy -ExecutionPolicy Unrestricted -Scope LocalMachine"
#     - powershell.exe ./CompileTest.ps1
#   - name: "Linux build"
#     os: linux
#     dotnet: 3.1
#     after_success:
#     - sudo chmod +x ./CompileTest.sh
#     - sudo ./CompileTest.sh


# script:
#   - dotnet restore
#   - dotnet clean -v m
#   - dotnet build
#   - dotnet test

# jobs:
#   include:
#   - os: windows
#     language: csharp
#     install:
#     - choco install dotnetcore-sdk
#     - dotnet restore
#     script:
#     - dotnet clean -v m
#     - dotnet build
#     - dotnet test
#     - powershell -c "Set-ExecutionPolicy -ExecutionPolicy Unrestricted -Scope LocalMachine"
#     - powershell ./CompileTest.ps1
#   - os: linux
#     language: csharp
#     dotnet: 3.1
#     mono: none
#     addons:
#       apt:
#         packages:
#         - coreutils
#     install:
#     - dotnet restore
#     script:
#     - dotnet clean -v m --nologo
#     - dotnet build --nologo
#     - dotnet test --nologo
#     - sudo chmod +x ./CompileTest.sh
#     - sudo ./CompileTest.sh
