language: csharp
mono: none
dotnet: 3.1
git:
  quiet: true

script:
  - dotnet restore
  - dotnet build
  - dotnet test Tests/*.Tests/*.csproj

global:
  - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=true
  - DOTNET_CLI_TELEMETRY_OPTOUT=1