language: csharp
mono: none
git:
  quiet: true

global:
- DOTNET_SKIP_FIRST_TIME_EXPERIENCE=true
- DOTNET_CLI_TELEMETRY_OPTOUT=1

jobs:
  include:
  - os: windows
    language: csharp
    install:
    - choco install dotnetcore-sdk
    script:
    - dotnet clean -v m
    - dotnet build
    - dotnet test
    - powershell -c "Set-ExecutionPolicy -ExecutionPolicy Unrestricted -Scope LocalMachine"
    - powershell ./CompileTest.ps1
  - os: linux
    language: csharp
    dotnet: 3.1
    mono: none
    addons:
      apt:
        packages:
        - coreutils
    install:
    - dotnet build --nologo
    - stage: "Clean"
    script:  dotnet clean -v m --nologo
    - stage: "Build"
    - stage: "Test" 
    script: dotnet test --nologo
    script: sudo chmod +x ./CompileTest.sh
    script: sudo ./CompileTest.sh
