language: csharp
mono: none
dotnet: 3.1
os: 
- windows
- linux
- osx
git:
  quiet: true

global:
- DOTNET_SKIP_FIRST_TIME_EXPERIENCE=true
- DOTNET_CLI_TELEMETRY_OPTOUT=1

matrix:
  include:
    if: os = windows
      install:
      - choco install dotnetcore-sdk
      - dotnet restore
    script:
    - dotnet restore
    - dotnet clean -v m
    - dotnet build
    - dotnet test
    if: os = windows
      script:
      - powershell -c "Set-ExecutionPolicy -ExecutionPolicy Unrestricted -Scope LocalMachine"
      - powershell ./CompileTest.ps1
    if: os = linux
    - sudo chmod +x ./CompileTest.sh
    - sudo ./CompileTest.sh
    if: os = osx
    - sudo chmod +x ./CompileTest.sh
    - sudo ./CompileTest.sh
  # - os: linux
  #   language: csharp
  #   dotnet: 3.1
  #   mono: none
  #   addons:
  #     apt:
  #       packages:
  #       - coreutils
  #   install:
  #   - dotnet restore
  #   script:
  #   - dotnet clean -v m --nologo
  #   - dotnet build --nologo
  #   - dotnet test --nologo
  #   - sudo chmod +x ./CompileTest.sh
  #   - sudo ./CompileTest.sh
