language: csharp
mono: none
dotnet: 3.1
git:
  quiet: true

global:
- DOTNET_SKIP_FIRST_TIME_EXPERIENCE=true
- DOTNET_CLI_TELEMETRY_OPTOUT=1

jobs:
  include:
  - os: windows
    install:
    - choco install dotnetcore-sdk
    script:
    - powershell -c "Set-ExecutionPolicy -ExecutionPolicy Unrestricted -Scope LocalMachine"
    - powershell ./CompileTest.ps1
  - os: linux
    addons:
      apt:
        packages:
        - coreutils
    script:
    - sudo chmod +x ./CompileTest.sh
    - sudo ./CompileTest.sh

install:
- dotnet restore
script:
- dotnet clean -v m
- dotnet build
- dotnet test