language: csharp
mono: none
dotnet: 3.1
git:
  quiet: true
os:
- linux
- windows

before_install:
- |-
  case $TRAVIS_OS_NAME in windows)
    choco install dotnetcore-sdk ;;
  esac

install:
- dotnet restore

script:
- dotnet clean
- dotnet build
- dotnet test Tests/*.Tests/*.csproj

global:
- DOTNET_SKIP_FIRST_TIME_EXPERIENCE=true
- DOTNET_CLI_TELEMETRY_OPTOUT=1
