language: csharp
mono: none
git:
  quiet: true

global:
- DOTNET_SKIP_FIRST_TIME_EXPERIENCE=true
- DOTNET_CLI_TELEMETRY_OPTOUT=1

jobs:
  include:
    - stage: Install
      os: windows
      language: csharp
      install:
      - choco install dotnetcore-sdk
      - dotnet restore
    - stage: Clean
      script:
      - dotnet clean -v m
    - stage: Build
      script:
      - dotnet build
    - stage: Test
      script:
      - dotnet test
      - powershell -c "Set-ExecutionPolicy -ExecutionPolicy Unrestricted -Scope LocalMachine"
      - powershell ./CompileTest.ps1
    - stage: Install
      os: linux
      language: csharp
      dotnet: 3.1
      mono: none
      addons:
        apt:
          packages:
          - coreutils
      install:
      - dotnet restore
    - stage: Clean
      script:
      - dotnet clean -v m --nologo
    - stage: Build
      script:
      - dotnet build --nologo
    - stage: Test
      script:
      - dotnet test --nologo
      - sudo chmod +x ./CompileTest.sh
      - sudo ./CompileTest.sh
