#include<Arduino.h>
//code generated by the PseudoIno compiler
void blink();
void setup();
void loop();
void setup()
{
pinMode(13, OUTPUT);
}
void blink()
{
digitalWrite(13,  1);
delay(1*1000);
digitalWrite(13,  0);
delay(1*1000);

}
void loop()
{
blink();

}
