#include<Arduino.h>
//code generated by the PseudoIno compiler
void setup();
void loop();
void setup()
{
int brightness = 0;
int amountToAdd = 5;
int a = 2 + 5;
pinMode(A9, OUTPUT);
}
void loop()
{
analogWrite(A9, 0);
if((brightness < 0) || (brightness > 255)){
amountToAdd = -1;

}
else{

}
else if ((amountToAdd < 2)){
amountToAdd = 0;

}
delay(30);

}
