#include<Arduino.h>
//code generated by the PseudoIno compiler
void trigger(int a, int b, int c );
void setup();
void loop();
void setup()
{
}
void trigger(int a, int b, int c )
{
int brightness = 0;
int amountToAdd = 5;
if((brightness < 0) || (brightness > 255)){
amountToAdd = -1;

}
else{

}
else if ((brightness = 0)){
amountToAdd = 1;

}
else{
amountToAdd = 5;

}

}
void loop()
{
bool a =  1;
float b = 3.3;
int c = 1;
trigger(a, b, c);

}
