#include<Arduino.h>
//code generated by the PseudoIno compiler
void setup();
void loop();
void setup()
{
pinMode(13, OUTPUT);
}
void loop()
{
digitalWrite(13,  1);
delay(500);
digitalWrite(13,  0);
delay(1500);
digitalWrite(13,  1);
delay(500);
digitalWrite(13,  0);
delay(200);
digitalWrite(13,  1);
delay(500);
digitalWrite(13,  0);
delay(200);
digitalWrite(13,  1);
delay(500);
digitalWrite(13,  0);
delay(1500);
digitalWrite(13,  1);
delay(200);
digitalWrite(13,  0);
delay(1500);
digitalWrite(13,  1);
delay(500);
digitalWrite(13,  0);
delay(1500);
digitalWrite(13,  1);
delay(200);
digitalWrite(13,  0);
delay(1500);
digitalWrite(13,  1);
delay(500);
digitalWrite(13,  0);
delay(1500);
digitalWrite(13,  1);
delay(200);
digitalWrite(13,  0);
delay(1500);
digitalWrite(13,  1);
delay(200);
digitalWrite(13,  0);
delay(1500);
digitalWrite(13,  1);
delay(200);
digitalWrite(13,  0);
delay(1500);
digitalWrite(13,  1);
delay(200);
digitalWrite(13,  0);
delay(1500);
digitalWrite(13,  1);
delay(500);
digitalWrite(13,  0);
delay(1500);
digitalWrite(13,  1);
delay(200);
digitalWrite(13,  0);
delay(1500);

}
